ProjectManager.Web/Controllers/BoardController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ProjectManager.Domain;
using ProjectManager.Services;
using ProjectManager.Web.Models;
using ProjectManager.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectManager.Web.Controllers
{
    public class BoardController : Controller
    {
        private readonly IProjectManagerRepository repository;
        private readonly IMapper mapper;

        public BoardController(IProjectManagerRepository repository, IMapper mapper)
        {
            this.repository = repository ?? throw new ArgumentNullException(nameof(repository));
            this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        public IActionResult Index()
        {
            var viewModel = new BoardIndexViewModel();
            var sections = repository.GetBoardSections(includeTasks: true, includeTaskProject:true);
            viewModel.Sections = mapper.Map<List<BoardSectionModel>>(sections);
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult AddSection(BoardIndexViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("index", viewModel);
            }

            var section = new BoardSectionModel
            {
                Name = viewModel.SectionCreateViewModel.Name
            };

            var sectionToAdd = mapper.Map<BoardSection>(section);
            repository.AddBoardSection(sectionToAdd);
            repository.Save();
            return RedirectToAction("Index");
        }

        public IActionResult DeleteSection(Guid id, string redirectUrl)
        {
            var section = repository.GetBoardSectionById(id,includeTasks:true);
            if(section!= null)
            {
                if (section.Tasks.Count > 0)
                {
                    ViewBag.ErrorTitle = "this section has tasks in it, please delete the tasks first";
                    return View("Error");
                }
                repository.DeleteBoardSection(section);
                repository.Save();
            }
            return LocalRedirect(redirectUrl);
        }

        public IActionResult EditSection(Guid id)
        {
            var section = repository.GetBoardSectionById(id);
            if (section == null)
            {
                ViewBag.ErrorMessage = "the given section was not found";
                return View("NotFound");
            }
            var _section = mapper.Map<BoardSectionModel>(section);
            var viewModel = new BoardSectionEditViewModel
            {
                Id = _section.Id,
                Name = _section.Name,
            };
            return View(viewModel);

        }
        [HttpPost]
        public IActionResult EditSection(BoardSectionEditViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }
            var section = repository.GetBoardSectionById(viewModel.Id);
            if (section != null)
            {
                section.Name = viewModel.Name;
                repository.Save();
            }
            return RedirectToAction("Index");
        }


    }
}

ProjectManager.Web/Controllers/MemberController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectManager.Domain;
using ProjectManager.Services;
using ProjectManager.Web.Models;
using ProjectManager.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectManager.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MemberController : Controller
    {
        private readonly IProjectManagerRepository repository;
        private readonly IMapper mapper;

        public MemberController(IProjectManagerRepository repository, IMapper mapper)
        {
            this.repository = repository ?? throw new ArgumentNullException(nameof(repository));
            this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        public IActionResult Index()
        {
            var viewModel = new MemberIndexViewModel();
            var persons = repository.GetUsers();
            var members = mapper.Map<List<Member>>(persons);
            viewModel.Members = members;
            return View(viewModel);
        }

        public IActionResult CreateMember()
        {
            var viewModel = new MemberCreateViewModel();
            return View(viewModel);
        }


        [HttpPost]
        public IActionResult CreateMember(MemberCreateViewModel viewmodel)
        {
            
            return RedirectToAction("Index");
        }

        public IActionResult DeleteMember(Guid id)
        {
            
            return RedirectToAction("Index");
        }
        
    }
}

ProjectManager.Web/Controllers/TaskController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjectManager.Domain;
using ProjectManager.Services;
using ProjectManager.Web.DTO;
using ProjectManager.Web.Models;
using ProjectManager.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ProjectManager.Web.Controllers
{
    public class TaskController : Controller
    {
        private readonly IProjectManagerRepository repository;
        private readonly IMapper mapper;

        public TaskController(IProjectManagerRepository repository, IMapper mapper)
        {
            this.repository = repository ?? throw new ArgumentNullException(nameof(repository));
            this.mapper = mapper ?? throw new ArgumentNullException(nameof(repository));
        }


        [HttpPost]
        public IActionResult AddTask(Guid id, ProjectDetailsViewModel viewmodel)
        {

            var task = new TaskModel()
            {
                UserId = viewmodel.TaskCreateViewModel.Assigne,
                Name = viewmodel.TaskCreateViewModel.Name,
                Description = viewmodel.TaskCreateViewModel.Description,
                DueDate = viewmodel.TaskCreateViewModel.DueDate,

            };
            var taskToAdd = mapper.Map<Task>(task);
            repository.AddTask(taskToAdd, viewmodel.TaskCreateViewModel.Section, viewmodel.TaskCreateViewModel.BoardSection);
            repository.Save();
            return RedirectToAction("ProjectDetails", "Project", new { id = id });
        }

        public IActionResult ToggleTaskCompletion(Guid id, string redirectUrl)
        {
            var task = repository.GetTaskById(id);
            if (task != null)
            {
                task.CompletionStatus = !task.CompletionStatus;
                repository.Save();
            }

            return LocalRedirect(redirectUrl);
        }

        public IActionResult UpdateTaskSection(Guid id, Guid sectionId, string type)
        {
            object section = null;
            bool isBoardSection = false;
            var task = repository.GetTaskById(id, includeSection: true, includeMainSection: true);
            if (!string.IsNullOrWhiteSpace(type))
            {
                if (type.ToLower() == "project")
                {
                    section = repository.GetSectionById(sectionId);
                }
                else if (type.ToLower() == "board")
                {
                    section = repository.GetBoardSectionById(sectionId);
                    isBoardSection = true;
                }
            }
            else
            {
                return BadRequest("request was made from unknown controller");
            }

            if (task != null && section != null)
            {
                if (isBoardSection)
                {
                    var _section = section as BoardSection;
                    task.BoardSection = _section;
                }
                else
                {
                    var _section = section as ProjectSection;
                    task.Section = _section;
                }
                repository.Save();
                return Ok(new { statuscode = StatusCodes.Status200OK, message = "task section updated successfully" });
            }
            return NotFound(new { statuscode = StatusCodes.Status404NotFound, message = "task or section not found" });
        }

        public IActionResult DeleteTask(Guid id, string redirectUrl)
        {
            var task = repository.GetTaskById(id);
            if (task != null)
            {
                repository.DeleteTask(task);
                repository.Save();
            }
            return LocalRedirect(redirectUrl);
        }

        public IActionResult EditTask(Guid id, string requestUrl = default)
        {
            var _a = Request;
            var task = mapper.Map<TaskModel>(repository.GetTaskById(id, includeProject: true, includeUser: true
                , includeSection: true, includeMainSection: true));
            var members = mapper.Map<List<Member>>(repository.GetUsers());
            var sections = mapper.Map<List<SectionModel>>(repository.GetSectionForProject(task.Project.Id));
            var boardSections = mapper.Map<List<BoardSectionModel>>(repository.GetBoardSections());
            var viewModel = new TaskEditViewModel(task, members,sections, boardSections, task.Project.Id);
            viewModel.ReturnUrl = requestUrl;
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult EditTask(TaskEditViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
               
                var members = mapper.Map<List<Member>>(repository.GetUsers());
                var sections = mapper.Map<List<SectionModel>>(repository.GetSectionForProject(viewModel.TaskProjectId));
                var boardSections = mapper.Map<List<BoardSectionModel>>(repository.GetBoardSections());
                viewModel.Generate(members,sections,boardSections);
                return View(viewModel);
            }
            var task = mapper.Map<TaskEditDto>(viewModel);
            var _task = repository.GetTaskById(viewModel.Id, includeProject: true,
                includeSection: true, includeMainSection: true);
            mapper.Map(task, _task);
            var section = repository.GetSectionById(viewModel.Section);
            var boardSection = repository.GetBoardSectionById(viewModel.BoardSection);
            _task.Section = section;
            _task.BoardSection = boardSection;
            repository.Save();


            if (viewModel.ReturnUrl != default)
                return LocalRedirect(viewModel.ReturnUrl);
            return RedirectToAction("Index", "Home");
        }


    }
}

ProjectManager.Web/Controllers/TeamController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectManager.Domain;
using ProjectManager.Services;
using ProjectManager.Web.Models;
using ProjectManager.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectManager.Web.Controllers
{
    public class TeamController : Controller
    {
        private readonly IProjectManagerRepository repository;
        private readonly IMapper mapper;

        public TeamController(IProjectManagerRepository repository, IMapper mapper)
        {
            this.repository = repository ?? throw new ArgumentNullException(nameof(repository));
            this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        public IActionResult Index()
        {
            var viewModel = new TeamIndexViewModel();
            var teams = mapper.Map<List<TeamModel>>(repository.GetTeams());
            viewModel.Teams = teams;
            return View(viewModel);
        }

        public IActionResult CreateTeam()
        {
            var members = mapper.Map<List<Member>>(repository.GetUsers());
            var viewModel = new TeamCreateViewModel(members);
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult CreateTeam(TeamCreateViewModel viewModel)
        {
            
            var team = new TeamModel()
            {
                Name = viewModel.Name,
            };
            var teamToAdd = mapper.Map<Team>(team);

            repository.AddTeam(teamToAdd, viewModel.SelectedMembers);
            repository.Save();

            return RedirectToAction("Index");
        }

        public IActionResult DeleteTeam(Guid id)
        {
            var team = repository.GetTeamById(id);
            if(team != null)
            {
                repository.DeleteTeam(team);
                repository.Save();
            }
            return RedirectToAction("Index");
        }


        public IActionResult EditTeam(Guid id)
        {
            var team = repository.GetTeamById(id, includeUsers: true);
            if(team == null)
            {
                ViewBag.ErrorMessage = "Team not found";
                return View("NotFound");
            }
            var teamModel = mapper.Map<TeamModel>(team);
            var members = mapper.Map<List<Member>>(repository.GetUsers());
            var viewModel = new TeamEditViewModel(teamModel, members);

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult EditTeam(Guid id, TeamEditViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Id = id;
                return View(viewModel);
            }
            var team = repository.GetTeamById(id,includeUsers:true);
            if(team == null)
            {
                ViewBag.ErrorMessage = "Team Not Found";
                return View("NotFound");
            }
            team.Name = viewModel.Name;
            var members = new List<ApplicationUser>();
            foreach (var memberId in viewModel.SelectedMembers)
            {
                members.Add(repository.GetUserById(memberId));
            }
            team.User = members;
            repository.UpdateTeam(team);
            repository.Save();
            return RedirectToAction("Index");
        }

    }
}

ProjectManager.Web/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "NotFound Page";
}
<div class="text-center">
    <h1 class="display-4">Not Found</h1>
    <p>@ViewBag.ErrorMessage<a asp-action="Index" asp-controller="Home">Return to Home page.</a></p>
</div>

ProjectManager.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OffBeat.PM</title>

    <link rel="stylesheet" href="~/multiselect/example-styles.css" />
    <link rel="stylesheet" href="~/bootstrap-icons/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <!-- Favicons -->
    <link rel="shortcut icon" href="~/img/favicon-16x16.png">
    <link rel="icon" href="~/img/icon.png">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/img/logo1.png" alt="logo icon">
                    OffBeat.PM
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Admin") || User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Team" asp-action="Index">Teams</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Projects</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Board" asp-action="Index">Board</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="Index">Members</a>
                            </li>
                        }


                    </ul>
                    @if (!User.Identity.IsAuthenticated)
                    {
                    <ul class="nav justify-content-end">
                        <li class="nav-item">
                            <a class="btn btn-outline-primary" asp-action="Login" asp-controller="Account">Login</a>
                        </li>
                    </ul>
            }
            else
            {
                <ul class="nav justify-content-end">
                    <li>
                        <span>Welcome @User.Identity.Name</span>
                        <a class="btn btn-outline-danger" asp-action="Logout" asp-controller="Account">Logout</a>
                    </li>
                </ul>
            }
                </div>

                @*<a class="btn btn-outline-primary" asp-action="Login" asp-controller="User">Login</a>*@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - OffBeat.PM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.esm.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/multiselect/jquery.multi-select.js"></script>


    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>

ProjectManager.Web/Views/Shared/_MainBoardPartial.cshtml
@model List<BoardSectionModel>

<div class="container-fluid pt-3">

    <div class="row flex-row flex-sm-nowrap py-3 overflow-auto">
        @foreach (var section in Model)
        {
            var requestPath = Url.ActionContext.HttpContext.Request.Path.ToString();
            <div class="col-sm-6 col-md-4 col-xl-3">
                <div class="card">
                    <div class="card-body">
                        <h6 class="card-title text-uppercase text-truncate py-2">
                            @(section.Name)
                            <a asp-controller="Board" asp-action="EditSection"
                               asp-route-id="@(section.Id)"><i class="bi bi-three-dots text-black"></i></a>
                            <button id="submitDelete" class="close" data-target="#deletemodal" data-toggle="modal"
                                    onclick="window.click(this)" asp-controller="Board" asp-action="DeleteSection" asp-route-id="@(section.Id)"
                                    asp-route-redirectUrl="@requestPath">
                                &times;
                            </button>
                        </h6>
                        <hr />
                        <div class="items" id="@(section.Id)">

                            @foreach (var task in section.Tasks)
                            {
                                var completion = task.CompletionStatus ? "completed" : "incompleted";
                                
                                <div class="dropzone rounded" ondrop="drop(event)" ondragover="allowDrop(event)" ondragleave="clearDrop(event)"> &nbsp; </div>
                                <div class="card draggable" id="@("task"+task.Id)" draggable="true" ondragstart="drag(event)">
                                    <div class="card-body p-2">
                                        <div class="card-title">
                                            <a class="btn btn-circle btn-outline-success float-right @completion"
                                               asp-controller="Task"
                                               asp-action="ToggleTaskCompletion"
                                               asp-route-id="@task.Id"
                                               asp-route-redirectUrl="@requestPath">
                                                <i class="bi-check-lg"></i>
                                            </a>
                                            <p class="lead font-weight-light">@task.Name</p>
                                            <a asp-controller="Project" asp-action="ProjectDetails" asp-route-id="@task.Project.Id" 
                                               class="lead font-weight-light text-black" >Project: @task.Project.Name</a>
                                        </div>
                                        <p>
                                            @task.Description
                                        </p>
                                        <input asp-for="@task.Section.Id" id="@("task"+task.Id+"section")" hidden />
                                        <a class="btn btn-outline-info" asp-controller="Task" asp-action="EditTask" asp-route-id="@task.Id"
                                           asp-route-requestUrl="@requestPath">Details</a>
                                        <button id="submitDelete" class="btn btn-outline-danger" data-target="#deletemodal" data-toggle="modal"
                                                onclick="window.click(this)" asp-controller="Task" asp-action="DeleteTask" asp-route-id="@task.Id"
                                                asp-route-redirectUrl="@requestPath">
                                            Delete
                                        </button>
                                    </div>
                                </div>
                                <div class="dropzone rounded" ondrop="drop(event)" ondragover="allowDrop(event)" ondragleave="clearDrop(event)"> &nbsp; </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</div>

ProjectManager.Web/Views/Shared/_TaskBoardPartial.cshtml
@model List<SectionModel>

<div class="container-fluid pt-3">

    <div class="row flex-row flex-sm-nowrap py-3 overflow-auto">
        @foreach (var section in Model)
        {
            var requestPath = Url.ActionContext.HttpContext.Request.Path.ToString();
            <div class="col-sm-6 col-md-4 col-xl-3">
                <div class="card">
                    <div class="card-body">
                        <h6 class="card-title text-uppercase text-truncate py-2">
                            @(section.Name)
                            <a asp-controller="Section" asp-action="EditSection"
                               asp-route-id="@(section.Id)"><i class="bi bi-three-dots text-black"></i></a>
                            <button id="submitDelete" class="close" data-target="#deletemodal" data-toggle="modal"
                                    onclick="window.click(this)" asp-controller="Section" asp-action="DeleteSection" asp-route-id="@(section.Id)"
                                    asp-route-redirectUrl="@requestPath">
                                &times;
                            </button>
                        </h6>
                        <hr />
                        <div class="items" id="@(section.Id)">

                            @foreach (var task in section.Tasks)
                            {
                                var completion = task.CompletionStatus ? "completed" : "incompleted";
                               
                                <div class="dropzone rounded" ondrop="drop(event)" ondragover="allowDrop(event)" ondragleave="clearDrop(event)"> &nbsp; </div>
                                <div class="card draggable" id="@("task"+task.Id)" draggable="true" ondragstart="drag(event)">
                                    <div class="card-body p-2">
                                        <div class="card-title">
                                            <a class="btn btn-circle btn-outline-success float-right @completion"
                                               asp-controller="Task"
                                               asp-action="ToggleTaskCompletion"
                                               asp-route-id="@task.Id"
                                               asp-route-redirectUrl="@requestPath">
                                                <i class="bi-check-lg"></i>
                                            </a>
                                            <p class="lead font-weight-light">@task.Name</p>
                                        </div>
                                        <p>
                                            @task.Description
                                        </p>
                                        <input asp-for="@task.Section.Id" id="@("task"+task.Id+"section")" hidden />
                                        <a class="btn btn-outline-info" asp-controller="Task" asp-action="EditTask" asp-route-id="@task.Id"
                                           asp-route-requestUrl="@requestPath">Details</a>
                                        <button id="submitDelete" class="btn btn-outline-danger" data-target="#deletemodal" data-toggle="modal"
                                                onclick="window.click(this)" asp-controller="Task" asp-action="DeleteTask" asp-route-id="@task.Id"
                                                asp-route-redirectUrl="@requestPath">
                                            Delete
                                        </button>
                                    </div>
                                </div>
                                <div class="dropzone rounded" ondrop="drop(event)" ondragover="allowDrop(event)" ondragleave="clearDrop(event)"> &nbsp; </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</div>

ProjectManager.Web/Views/Shared/_TasksListPartial.cshtml
@model List<SectionModel>



@foreach (var section in Model)
{
    var requestPath = Url.ActionContext.HttpContext.Request.Path.ToString();
    <hr />
    <a class="text-black" data-toggle="collapse" href="@("#table"+section.Id)" role="button" aria-expanded="false"
       aria-controls="@("table"+section.Id)">
        <i class="bi bi-caret-right-fill"></i>@(section.Name)

    </a>
    <a asp-controller="Section" asp-action="EditSection"
       asp-route-id="@(section.Id)"><i class="bi bi-three-dots text-black"></i></a>

    <button id="submitDelete" class="close" data-target="#deletemodal" data-toggle="modal"
            onclick="window.click(this)" asp-controller="Section" asp-action="DeleteSection" asp-route-id="@(section.Id)"
            asp-route-redirectUrl="@requestPath">
        &times;
    </button>


    <div class="collapse @(section.Tasks.Count>0?"show":"")" id="@("table"+section.Id)">
        <table class="table">
            <thead>
                <tr class="col-12">
                    <th class="col-5 text-left">Name</th>
                    <th class="col-4 text-left">Due Date</th>
                    <th class="col-1 text-center">Completed</th>
                    <th class="text-right col-2">Actions</th>
                </tr>
            </thead>
            <tbody>
                @if (section.Tasks != null && section.Tasks.Count > 0)
                {
                    @foreach (var task in section.Tasks)
                    {
                        var completion = task.CompletionStatus ? "completed" : "incompleted";
                        
                        <tr>
                            <td>@task.Name</td>
                            <td>
                                @task.DueDate
                            </td>
                            <td class="text-center">

                                <a class="btn btn-circle btn-outline-success @completion" asp-controller="Task"
                                   asp-action="ToggleTaskCompletion"
                                   asp-route-id="@task.Id"
                                   asp-route-redirectUrl="@requestPath">
                                    <i class="bi-check-lg"></i>
                                </a>


                            </td>
                            <td class="text-right">

                                <a class="btn btn-outline-info" asp-controller="Task" asp-action="EditTask" asp-route-id="@task.Id"
                                   asp-route-requestUrl="@requestPath">Details</a>
                                <button id="submitDelete" class="btn btn-outline-danger" data-target="#deletemodal" data-toggle="modal"
                                        onclick="window.click(this)" asp-controller="Task" asp-action="DeleteTask" asp-route-id="@task.Id"
                                        asp-route-redirectUrl="@requestPath">
                                    Delete
                                </button>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
}