ProjectManager.Web/ViewModels/ProjectDetailsViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectManager.Domain;
using ProjectManager.Web.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

namespace ProjectManager.Web.ViewModels
{
    public class ProjectDetailsViewModel
    {
        public TaskCreateViewModel TaskCreateViewModel { get; set; }
        public SectionCreateViewModel SectionCreateViewModel { get; set; }
        public ProjectModel Project { get; set; }

        public ProjectDetailsViewModel(ProjectModel project)
        {
            SectionCreateViewModel = new SectionCreateViewModel();
            TaskCreateViewModel = new TaskCreateViewModel();
            Project = project;
        }
        public ProjectDetailsViewModel(ProjectModel project, TaskCreateViewModel viewModel)
        {
            SectionCreateViewModel = new SectionCreateViewModel();
            TaskCreateViewModel = viewModel;
            Project = project;
        }
        public ProjectDetailsViewModel()
        {
        }
    }
}

ProjectManager.Web/Controllers/ProjectController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProjectManager.Domain;
using ProjectManager.Services;
using ProjectManager.Web.Models;
using ProjectManager.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


namespace ProjectManager.Web.Controllers
{
    
    public class ProjectController : Controller
    {
        private readonly IProjectManagerRepository repository;
        private readonly IMapper mapper;

        public ProjectController(IProjectManagerRepository repository, IMapper mapper)
        {
            this.repository = repository ?? throw new ArgumentNullException(nameof(repository));
            this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));

        }
        public IActionResult Index()
        {
            var projects = repository.GetProjects().ToList();
            var viewModel = new ProjectIndexViewModel()
            {
                Projects = mapper.Map<List<ProjectModel>>(projects)
            };
            return View(viewModel);
        }


        [Authorize(Roles = "Admin")]
        public IActionResult CreateProject()
        {
            
            var teams = repository.GetTeams();
            var teamsList = mapper.Map<List<TeamModel>>(teams);
            var viewModel = new ProjectCreateViewModel(teamsList);
            return View(viewModel);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult CreateProject(ProjectCreateViewModel viewModel)
        {
   
            var project = new ProjectModel()
            {
                Name = viewModel.Name,
            };

            var projectToAdd = mapper.Map<Project>(project);
            repository.AddProject(projectToAdd, viewModel.SelectedTeams);
            repository.Save();

            return RedirectToAction("Index");
        }

        [Authorize( Roles = "Admin")]
        public IActionResult EditProject(Guid id)
        {
            var project = repository.GetProjectById(id, includeTeams: true);
            if (project == null)
            {
                ViewBag.ErrorMessage = "Project Not Found";
                return View("NotFound");
            }
            var projectModel = mapper.Map<ProjectModel>(project);
            var teams = mapper.Map<List<TeamModel>>(repository.GetTeams());
            var viewModel = new ProjectEditViewModel(projectModel, teams);

            return View(viewModel);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult EditProject(Guid id, ProjectEditViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Id = id;
                return View(viewModel);
            }
            var project = repository.GetProjectById(id, includeTeams: true);
            if (project == null)
            {
                ViewBag.ErrorMessage = "Project Not Found";
                return View("NotFound");
            }
            project.Name = viewModel.Name;
            var teams = new List<Team>();
            foreach (var teamId in viewModel.SelectedTeams)
            {
                teams.Add(repository.GetTeamById(teamId));
            }
            project.Teams = teams;
            repository.UpdateProject(project);
            repository.Save();
            return RedirectToAction("Index");
        }


        [Authorize(Roles = "Admin")]
        public IActionResult DeleteProject(Guid id)
        {
            var project = repository.GetProjectById(id);
            if (project != null)
            {
                repository.DeleteProject(project);
                repository.Save();
            }
            return RedirectToAction("Index");
        }


        public IActionResult ProjectDetails(Guid id)
        {
            
            var project = mapper.Map<ProjectModel>(repository.GetProjectById(id,includeTasks: true, includeTeams: true, includeSections: true));
            if(project == null)
            {
                return View("NotFound");
            }
            project.Tasks = project.Tasks.OrderBy(p => p.DueDate).ToList();
            var members = mapper.Map<List<Member>>( repository.GetUsersForProject(id));
            var boardSections = mapper.Map<List<BoardSectionModel>>(repository.GetBoardSections());
            var creatTaskViewModel = new TaskCreateViewModel(members, project,boardSections);
            var viewModel = new ProjectDetailsViewModel(project,creatTaskViewModel);
            return View(viewModel);
        }

       

    }
}

ProjectManager.Web/Controllers/ProjectDetailsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ProjectManager.Services;
using ProjectManager.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectManager.Web.Controllers
{
   // [Route("Project/[controller]/{projectId}",Name ="ProjectDetails")]
    public class ProjectDetailsController:Controller
    {
        private readonly IProjectManagerRepository repository;
        private readonly IMapper mapper;

        public ProjectDetailsController(IProjectManagerRepository repository, IMapper mapper)
        {
            this.repository = repository ?? throw new ArgumentNullException(nameof(repository));
            this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        public IActionResult Index(Guid projectId)
        {
            var project = mapper.Map<ProjectModel>(repository.GetProjectById(projectId));
            if (project == null)
            {
                return View("NotFound");
            }
            return View(project);        
        
        }
        
    }
}

ProjectManager.Web/Controllers/SectionController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ProjectManager.Domain;
using ProjectManager.Services;
using ProjectManager.Web.Models;
using ProjectManager.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectManager.Web.Controllers
{
    public class SectionController : Controller
    {
        private readonly IProjectManagerRepository repository;
        private readonly IMapper mapper;

        public SectionController(IProjectManagerRepository repository, IMapper mapper)
        {
            this.repository = repository ?? throw new ArgumentNullException(nameof(repository));
            this.mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        [HttpPost]
        public IActionResult AddSection(Guid id, ProjectDetailsViewModel viewmodel)
        {

            var section = new SectionModel()
            {
                Name = viewmodel.SectionCreateViewModel.Name
            };
            var sectionToAdd = mapper.Map<ProjectSection>(section);
            repository.AddSection(id,sectionToAdd);
            repository.Save();
            return RedirectToAction("ProjectDetails", "Project", new { id = id });
        }

        public IActionResult EditSection(Guid id)
        {
            var section = repository.GetSectionById(id);
            if (section == null)
            {
                ViewBag.ErrorMessage = "the given section was not found";
                return View("NotFound");
            }
            var _section = mapper.Map<SectionModel>(section);
            var viewModel = new SectionEditViewModel
            {
                Id = _section.Id,
                Name = _section.Name,
                ProjectId = _section.ProjectId
            };
            return View(viewModel);
         }

        [HttpPost]
        public IActionResult EditSection(SectionEditViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }
            var section = repository.GetSectionById(viewModel.Id);
            if(section != null)
            {
                section.Name = viewModel.Name;
                repository.Save();
            }
            return RedirectToAction("ProjectDetails", "Project", new { id = viewModel.ProjectId });
        }

        public IActionResult DeleteSection(Guid id, string redirectUrl)
        {
            var section = repository.GetSectionById(id);
            if(section != null)
            {
                repository.DeleteSection(section);
                repository.Save();
            }
            return LocalRedirect(redirectUrl);
        }
    }
}

ProjectManager.Web/Controllers/TaskController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjectManager.Domain;
using ProjectManager.Services;
using ProjectManager.Web.DTO;
using ProjectManager.Web.Models;
using ProjectManager.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ProjectManager.Web.Controllers
{
    public class TaskController : Controller
    {
        private readonly IProjectManagerRepository repository;
        private readonly IMapper mapper;

        public TaskController(IProjectManagerRepository repository, IMapper mapper)
        {
            this.repository = repository ?? throw new ArgumentNullException(nameof(repository));
            this.mapper = mapper ?? throw new ArgumentNullException(nameof(repository));
        }


        [HttpPost]
        public IActionResult AddTask(Guid id, ProjectDetailsViewModel viewmodel)
        {

            var task = new TaskModel()
            {
                UserId = viewmodel.TaskCreateViewModel.Assigne,
                Name = viewmodel.TaskCreateViewModel.Name,
                Description = viewmodel.TaskCreateViewModel.Description,
                DueDate = viewmodel.TaskCreateViewModel.DueDate,

            };
            var taskToAdd = mapper.Map<Task>(task);
            repository.AddTask(taskToAdd, viewmodel.TaskCreateViewModel.Section, viewmodel.TaskCreateViewModel.BoardSection);
            repository.Save();
            return RedirectToAction("ProjectDetails", "Project", new { id = id });
        }

        public IActionResult ToggleTaskCompletion(Guid id, string redirectUrl)
        {
            var task = repository.GetTaskById(id);
            if (task != null)
            {
                task.CompletionStatus = !task.CompletionStatus;
                repository.Save();
            }

            return LocalRedirect(redirectUrl);
        }

        public IActionResult UpdateTaskSection(Guid id, Guid sectionId, string type)
        {
            object section = null;
            bool isBoardSection = false;
            var task = repository.GetTaskById(id, includeSection: true, includeMainSection: true);
            if (!string.IsNullOrWhiteSpace(type))
            {
                if (type.ToLower() == "project")
                {
                    section = repository.GetSectionById(sectionId);
                }
                else if (type.ToLower() == "board")
                {
                    section = repository.GetBoardSectionById(sectionId);
                    isBoardSection = true;
                }
            }
            else
            {
                return BadRequest("request was made from unknown controller");
            }

            if (task != null && section != null)
            {
                if (isBoardSection)
                {
                    var _section = section as BoardSection;
                    task.BoardSection = _section;
                }
                else
                {
                    var _section = section as ProjectSection;
                    task.Section = _section;
                }
                repository.Save();
                return Ok(new { statuscode = StatusCodes.Status200OK, message = "task section updated successfully" });
            }
            return NotFound(new { statuscode = StatusCodes.Status404NotFound, message = "task or section not found" });
        }

        public IActionResult DeleteTask(Guid id, string redirectUrl)
        {
            var task = repository.GetTaskById(id);
            if (task != null)
            {
                repository.DeleteTask(task);
                repository.Save();
            }
            return LocalRedirect(redirectUrl);
        }

        public IActionResult EditTask(Guid id, string requestUrl = default)
        {
            var _a = Request;
            var task = mapper.Map<TaskModel>(repository.GetTaskById(id, includeProject: true, includeUser: true
                , includeSection: true, includeMainSection: true));
            var members = mapper.Map<List<Member>>(repository.GetUsers());
            var sections = mapper.Map<List<SectionModel>>(repository.GetSectionForProject(task.Project.Id));
            var boardSections = mapper.Map<List<BoardSectionModel>>(repository.GetBoardSections());
            var viewModel = new TaskEditViewModel(task, members,sections, boardSections, task.Project.Id);
            viewModel.ReturnUrl = requestUrl;
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult EditTask(TaskEditViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
               
                var members = mapper.Map<List<Member>>(repository.GetUsers());
                var sections = mapper.Map<List<SectionModel>>(repository.GetSectionForProject(viewModel.TaskProjectId));
                var boardSections = mapper.Map<List<BoardSectionModel>>(repository.GetBoardSections());
                viewModel.Generate(members,sections,boardSections);
                return View(viewModel);
            }
            var task = mapper.Map<TaskEditDto>(viewModel);
            var _task = repository.GetTaskById(viewModel.Id, includeProject: true,
                includeSection: true, includeMainSection: true);
            mapper.Map(task, _task);
            var section = repository.GetSectionById(viewModel.Section);
            var boardSection = repository.GetBoardSectionById(viewModel.BoardSection);
            _task.Section = section;
            _task.BoardSection = boardSection;
            repository.Save();


            if (viewModel.ReturnUrl != default)
                return LocalRedirect(viewModel.ReturnUrl);
            return RedirectToAction("Index", "Home");
        }


    }
}

ProjectManager.Web/Views/Project/CreateProject.cshtml
@model ProjectManager.Web.ViewModels.ProjectCreateViewModel

<form class="card shadow" method="post" asp-action="CreateProject" role="form" enctype="multipart/form-data">
    <h4 class="card-title" style="margin-left:1.25rem; margin-top:1.25rem;"><strong>Create Project</strong></h4>

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="card-body form-type-combine">
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <label asp-for="Name" class="require"></label>
                    <input type="text" class="form-control" asp-for="Name" required>
                    <span asp-validation-for="Name" class="text-danger invalid-feedback"></span>
                </div>
                <div class="form-group">
                    <label>Assigned Teams</label>
                    <select id="dropDownList" multiple asp-for="SelectedTeams" asp-items="@Model.Teams">
                    </select>
                </div>
            </div>
        </div>
    </div>


    <footer class="card-footer text-right">
        <a class="btn btn-outline-secondary" asp-action="Index">Cancel</a>
        <button class="btn btn-outline-primary" type="submit">Submit</button>
    </footer>
</form>

@section Scripts{

    @*<script>
        $(document).ready(function () {
            $('#dropDownList').multiSelect();
        });
    </script>*@
}

ProjectManager.Web/Views/Project/EditProject.cshtml
@model ProjectManager.Web.ViewModels.ProjectEditViewModel

<form class="card shadow" method="post" asp-action="EditProject" asp-route-id="@Model.Id" role="form" enctype="multipart/form-data">
    <h4 class="card-title" style="margin-left:1.25rem; margin-top:1.25rem;"><strong>Edit Project : @Model.Name</strong></h4>

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="card-body form-type-combine">
        <div class="row">
            <div class="col-12">
                <div class="form-group">
                    <label asp-for="Name" class="require"></label>
                    <input type="text" class="form-control" asp-for="Name" required>
                    <span asp-validation-for="Name" class="text-danger invalid-feedback"></span>
                </div>
                <div class="form-group">
                    <label>Teams</label>
                    <select id="dropDownList" asp-for="SelectedTeams" asp-items="@Model.Teams" multiple
                            class="form-control">
                    </select>
                </div>
            </div>
        </div>
    </div>


    <footer class="card-footer text-right">
        <a class="btn btn-outline-secondary" asp-action="Index">Cancel</a>
        <button class="btn btn-outline-primary" type="submit">Submit</button>
    </footer>
</form>

ProjectManager.Web/Views/Project/ProjectDetails.cshtml
@model ProjectManager.Web.ViewModels.ProjectDetailsViewModel

@{
    ViewData["Title"] = $"{Model.Project.Name}";
}



<div class="card shadow">

    @*<h4 class="card-title" style="margin-left:1.25rem; margin-top:1.25rem;">
            <strong>@ViewData["Title"]</strong>
        </h4>*@
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow shadow mb-3">
        <div class="container">
            <!---Add the project logo in here-->
            <a class="navbar-brand">
                @*<img src="~/img/logo1.png" alt="logo icon">*@
                <i class="bi bi-layout-three-columns"></i>
                @ViewData["Title"]
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <a class="nav-item nav-link text-dark" id="overview-tab" data-toggle="tab" href="#overview" role="tab" aria-controls="overview" aria-selected="true">Overview</a>
                    <a class="nav-item nav-link text-dark active" id="list-tab" data-toggle="tab" href="#list" role="tab" aria-controls="list" aria-selected="false">List</a>
                    <a class="nav-item nav-link text-dark" id="board-tab" data-toggle="tab" href="#board" role="tab" aria-controls="board" aria-selected="false">Board</a>
                </div>
                <ul class="nav justify-content-end float-right">
                    <li class="nav-item">
                        <div class="btn-group dropdown">
                            <button id="open" data-toggle="modal" data-target="#addTaskmodal" class="btn btn-outline-primary">
                                Add Task
                            </button>
                            <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <div class="dropdown-menu">
                                <button id="open" data-toggle="modal" data-target="#addSectionmodal" class="dropdown-item">
                                    Add Section
                                </button>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade" id="overview" role="tabpanel" aria-labelledby="overview-tab">
            <div class="card-body">
                <p>@Model.Project.Name</p>
            </div>
        </div>
        <div class="tab-pane fade show active" id="list" role="tabpanel" aria-labelledby="list-tab">
            <div class="card-body">
                <partial name="_TasksListPartial" model="Model.Project.Sections" />
            </div>
        </div>

        <div class="tab-pane fade" id="board" role="tabpanel" aria-labelledby="board-tab">
            <div class="card-body">
                <partial name="_TaskBoardPartial" model="Model.Project.Sections" />
            </div>
        </div>
    </div>

    <div class="modal fade" tabindex="-1" role="dialog" id="addTaskmodal">
        <div class="modal-dialog" role="document">
            <form class="modal-content" method="post" asp-controller="Task" asp-action="AddTask" asp-route-id="@Model.Project.Id" role="form" enctype="multipart/form-data">
                <div class="modal-header">
                    <h4 class="modal-title text-left">New Task</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>

                </div>
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="modal-body form-type-combine">
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label asp-for="TaskCreateViewModel.Name" class="require"></label>
                                <input type="text" class="form-control" asp-for="TaskCreateViewModel.Name" required>
                                <span asp-validation-for="TaskCreateViewModel.Name" class="text-danger invalid-feedback"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="TaskCreateViewModel.DueDate" class="require"></label>
                                <input type="datetime-local" class="form-control" asp-for="TaskCreateViewModel.DueDate" required>
                                <span asp-validation-for="TaskCreateViewModel.DueDate" class="text-danger invalid-feedback"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="TaskCreateViewModel.Description" class=""></label>
                                <textarea type="text" class="form-control" asp-for="TaskCreateViewModel.Description"></textarea>
                                <span asp-validation-for="TaskCreateViewModel.Description" class="text-danger invalid-feedback"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="TaskCreateViewModel.Assigne"></label>
                                <select asp-for="TaskCreateViewModel.Assigne" asp-items="@Model.TaskCreateViewModel.TeamMembers">
                                </select>
                            </div>
                            <div class="form-group">
                                <label asp-for="TaskCreateViewModel.Section"></label>
                                <select asp-for="TaskCreateViewModel.Section" asp-items="@Model.TaskCreateViewModel.Sections">
                                </select>
                            </div>
                            <div class="form-group">
                                <label asp-for="TaskCreateViewModel.BoardSection"></label>
                                <select asp-for="TaskCreateViewModel.BoardSection" asp-items="@Model.TaskCreateViewModel.BoardSections">
                                </select>
                            </div>
                            <input asp-for="TaskCreateViewModel.ProjectId" hidden />
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-outline-primary">Submit</button>
                </div>

            </form>
        </div>
    </div>

    <div class="modal fade" tabindex="-1" role="dialog" id="deletemodal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 id="deletemodaltitle" class="modal-title text-left">Delete Task</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <strong class="text-danger">Are you sure you want to this item?</strong>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
                    <a id="deleteConfirmationSubmit" href="~/" class="btn btn-outline-danger">Delete</a>

                </div>

            </div>
        </div>
    </div>

    <div class="modal fade" tabindex="-1" role="dialog" id="addSectionmodal">
        <div class="modal-dialog" role="document">
            <form class="modal-content" method="post" asp-controller="Section" asp-action="AddSection" asp-route-id="@Model.Project.Id" role="form" enctype="multipart/form-data">
                <div class="modal-header">
                    <h4 class="modal-title text-left">New Section</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>

                </div>
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="modal-body form-type-combine">
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <label asp-for="SectionCreateViewModel.Name" class="require"></label>
                                <input type="text" class="form-control" asp-for="SectionCreateViewModel.Name" required>
                                <span asp-validation-for="SectionCreateViewModel.Name" class="text-danger invalid-feedback"></span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-outline-primary">Submit</button>
                </div>

            </form>
        </div>
    </div>
    
    <div class="modal fade" tabindex="-1" role="dialog" id="deleteSectionmodal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title text-left">Delete Section</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <strong class="text-danger">Are you sure you want to delete this section?</strong>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
                    <a id="deleteConfirmationSubmit" href="~/" class="btn btn-outline-danger">Delete</a>

                </div>

            </div>
        </div>
    </div>




</div>

@section Scripts{
<script type="text/javascript">
    $('.nav-tabs a').on('show.bs.tab', function (e) {
        const target = e.target.id;

        //get pane and modify its 
        //const targetpane = e.target.attributes.getNamedItem('href').value;
        //const targetpaneId = targetpane.substring(1);
        //const pane = document.getElementById(targetpaneId);
        //pane.innerHTML = 'nothing';
        //console.log(pane);
        if (target == 'list-tab') {
            window.location.reload();
        }
    });
</script>

}